/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package happybuttons;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Michael Balibrea
 */
public class SaveFrame extends javax.swing.JDialog {
    public static String profileName1 = "", profileName2 = "", profileName3 = "", profileName4 = "", profileName5 = "";
    public static String dbSlot1 = "", dbSlot2 = "", dbSlot3 = "", dbSlot4 = "", dbSlot5 = "";
    String theme = HappyButtons.uiTheme;
    /**
     * Creates new form Save
     */
    public SaveFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        super.setTitle("Save to profile");
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/3-this.getSize().height/2);
        
        // set frame icon
        ImageIcon imgIcon = new ImageIcon(HappyButtons.documentsPathDoubleSlash + Utility.strDoubleSlash("\\HappyButtons\\res\\icon\\wave.png"));
        setIconImage(imgIcon.getImage());
        
        setupTheme();
        
        reloadDB(HappyButtons.profileDB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        tfSaveProfile1 = new javax.swing.JTextField();
        btnSave1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panel6 = new javax.swing.JPanel();
        tfSaveProfile2 = new javax.swing.JTextField();
        btnSave2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panel7 = new javax.swing.JPanel();
        tfSaveProfile3 = new javax.swing.JTextField();
        btnSave3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panel8 = new javax.swing.JPanel();
        tfSaveProfile4 = new javax.swing.JTextField();
        btnSave4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panel9 = new javax.swing.JPanel();
        tfSaveProfile5 = new javax.swing.JTextField();
        btnSave5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(543, 212));
        setMinimumSize(new java.awt.Dimension(543, 212));
        setResizable(false);

        panel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tfSaveProfile1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSave1.setText("Save here");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SLOT 1");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSaveProfile1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(btnSave1)
                .addGap(41, 41, 41))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSaveProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tfSaveProfile2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSave2.setText("Save here");
        btnSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SLOT 2");

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSaveProfile2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(btnSave2)
                .addGap(41, 41, 41))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSaveProfile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tfSaveProfile3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSave3.setText("Save here");
        btnSave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SLOT 3");

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSaveProfile3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(btnSave3)
                .addGap(41, 41, 41))
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSaveProfile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tfSaveProfile4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSave4.setText("Save here");
        btnSave4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SLOT 4");

        javax.swing.GroupLayout panel8Layout = new javax.swing.GroupLayout(panel8);
        panel8.setLayout(panel8Layout);
        panel8Layout.setHorizontalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSaveProfile4))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel8Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(btnSave4)
                .addGap(41, 41, 41))
        );
        panel8Layout.setVerticalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSaveProfile4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tfSaveProfile5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSave5.setText("Save here");
        btnSave5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SLOT 5");

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSaveProfile5))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel9Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(btnSave5)
                .addGap(41, 41, 41))
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSaveProfile5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        DBOperations.indexDB = 0;
        Profile profile = new Profile();
        
        profileName1 = tfSaveProfile1.getText();
        
        if(profileName1.equals("")) {
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "Please provide SLOT 1 name", 
                "Empty name", 
                JOptionPane.WARNING_MESSAGE);
        }
        else if((profileName1.equalsIgnoreCase(dbSlot2) || profileName1.equalsIgnoreCase(dbSlot3) || 
                profileName1.equalsIgnoreCase(dbSlot4) || profileName1.equalsIgnoreCase(dbSlot5)) && 
                !profileName1.equals("")
                ) {
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "SLOT 1 name matches other slot name", 
                "Duplicate name", 
                JOptionPane.WARNING_MESSAGE);
        }
        else {
            HappyButtons.profileDB[0] = new ProfileDatabase();
            (HappyButtons.dbo).saveEnvironment(HappyButtons.profileDB, profile);
            
            this.dispose();
            
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "Profile saved!", 
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave2ActionPerformed
        DBOperations.indexDB = 1;
        Profile profile = new Profile();
        
        profileName2 = tfSaveProfile2.getText();
        
        if(profileName2.equals("")) {
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "Please provide SLOT 2 name", 
                "Empty name", 
                JOptionPane.WARNING_MESSAGE);
        }
        else if((profileName2.equalsIgnoreCase(dbSlot1) || profileName2.equalsIgnoreCase(dbSlot3) || 
                profileName2.equalsIgnoreCase(dbSlot4) || profileName2.equalsIgnoreCase(dbSlot5)) && 
                !profileName2.equals("")
                ) {
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "SLOT 2 name matches other slot name", 
                "Duplicate name", 
                JOptionPane.WARNING_MESSAGE);
        }
        else {
            HappyButtons.profileDB[1] = new ProfileDatabase();
            (HappyButtons.dbo).saveEnvironment(HappyButtons.profileDB, profile);
            
            this.dispose();
            
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "Profile saved!", 
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSave2ActionPerformed

    private void btnSave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave3ActionPerformed
        DBOperations.indexDB = 2;
        Profile profile = new Profile();
        
        profileName3 = tfSaveProfile3.getText();
        
        if(profileName3.equals("")) {
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "Please provide SLOT 3 name", 
                "Empty name", 
                JOptionPane.WARNING_MESSAGE);
        }
        else if((profileName3.equalsIgnoreCase(dbSlot1) || profileName3.equalsIgnoreCase(dbSlot2) || 
                profileName3.equalsIgnoreCase(dbSlot4) || profileName3.equalsIgnoreCase(dbSlot5)) && 
                !profileName3.equals("")
                ) {
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "SLOT 3 name matches other slot name", 
                "Duplicate name", 
                JOptionPane.WARNING_MESSAGE);
//            System.out.println("1: " + dbSlot1 + "\n2: " + dbSlot2 + "\n3: " + dbSlot3 + "\n4: " + dbSlot4 + "\n5: " + dbSlot5);
        }
        else {
            HappyButtons.profileDB[2] = new ProfileDatabase();
            (HappyButtons.dbo).saveEnvironment(HappyButtons.profileDB, profile);
            
            this.dispose();
            
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "Profile saved!", 
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSave3ActionPerformed

    private void btnSave4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave4ActionPerformed
        DBOperations.indexDB = 3;
        Profile profile = new Profile();
        
        profileName4 = tfSaveProfile4.getText();
        
        if(profileName4.equals("")) {
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "Please provide SLOT 4 name", 
                "Empty name", 
                JOptionPane.WARNING_MESSAGE);
        }
        else if((profileName4.equalsIgnoreCase(dbSlot1) || profileName4.equalsIgnoreCase(dbSlot2) || 
                profileName4.equalsIgnoreCase(dbSlot3) || profileName4.equalsIgnoreCase(dbSlot5)) && 
                !profileName4.equals("")
                ) {
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "SLOT 4 name matches other slot name", 
                "Duplicate name", 
                JOptionPane.WARNING_MESSAGE);
        }
        else {
            HappyButtons.profileDB[3] = new ProfileDatabase();
            (HappyButtons.dbo).saveEnvironment(HappyButtons.profileDB, profile);
            
            this.dispose();
            
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "Profile saved!", 
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSave4ActionPerformed

    private void btnSave5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave5ActionPerformed
        DBOperations.indexDB = 4;
        Profile profile = new Profile();
        
        profileName5 = tfSaveProfile5.getText();
        
        if(profileName5.equals("")) {
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "Please provide SLOT 5 name", 
                "Empty name", 
                JOptionPane.WARNING_MESSAGE);
        }
        else if((profileName5.equalsIgnoreCase(dbSlot1) || profileName5.equalsIgnoreCase(dbSlot2) || 
                profileName5.equalsIgnoreCase(dbSlot3) || profileName5.equalsIgnoreCase(dbSlot4)) && 
                !profileName5.equals("")
                ) {
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "SLOT 5 name matches other slot name", 
                "Duplicate name", 
                JOptionPane.WARNING_MESSAGE);
        }
        else {
            HappyButtons.profileDB[4] = new ProfileDatabase();
            (HappyButtons.dbo).saveEnvironment(HappyButtons.profileDB, profile);
            
            this.dispose();
            
            JOptionPane.showMessageDialog(HappyButtons.mf, 
                "Profile saved!", 
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSave5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaveFrame dialog = new SaveFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void reloadDB(ProfileDatabase profileDB[]){
        int loop;
        
        for(loop = 0; loop < 5; loop++){
            try{
                if(loop == 0){
                    if(profileDB[loop].getProfileName() == ""){
                        dbSlot1 = "";
                    }
                    else {
                        dbSlot1 = profileDB[loop].getProfileName();
                    }
                    
                    tfSaveProfile1.setText(dbSlot1);
                }
                else if(loop == 1){
                    if(profileDB[loop].getProfileName() == ""){
                        dbSlot2 = "";
                    }
                    else {
                        dbSlot2 = profileDB[loop].getProfileName();
                    }
                    
                    tfSaveProfile2.setText(dbSlot2);
                }
                else if(loop == 2){
                    if(profileDB[loop].getProfileName() == ""){
                        dbSlot3 = "";
                    }
                    else {
                        dbSlot3 = profileDB[loop].getProfileName();
                    }
                    
                    tfSaveProfile3.setText(dbSlot3);
                }
                else if(loop == 3){
                    if(profileDB[loop].getProfileName() == ""){
                        dbSlot4 = "";
                    }
                    else {
                        dbSlot4 = profileDB[loop].getProfileName();
                    }
                    
                    tfSaveProfile4.setText(dbSlot4);
                }
                else if(loop == 4){
                    if(profileDB[loop].getProfileName() == ""){
                        dbSlot5 = "";
                    }
                    else {
                        dbSlot5 = profileDB[loop].getProfileName();
                    }
                    
                    tfSaveProfile5.setText(dbSlot5);
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(HappyButtons.mf, 
                    "Databse might be renamed or changed externally or might be deleted\n\nSystem err:\n" + e.toString(), 
                    "Database error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void setupTheme() {
        if(theme.equals("light")) {
            // ------------------------------------------------------------------------------- PANELS
            this.getContentPane().setBackground(new JDialog().getBackground());
            
            panel1.setBackground(new JPanel().getBackground());
            panel1.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
            
            panel6.setBackground(new JPanel().getBackground());
            panel6.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
            
            panel7.setBackground(new JPanel().getBackground());
            panel7.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
            
            panel8.setBackground(new JPanel().getBackground());
            panel8.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
            
            panel9.setBackground(new JPanel().getBackground());
            panel9.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
            
            // ------------------------------------------------------------------------------- LABELS
            jLabel1.setBackground(new JLabel().getBackground());
            jLabel1.setForeground(new JLabel().getForeground());
            
            jLabel3.setBackground(new JLabel().getBackground());
            jLabel3.setForeground(new JLabel().getForeground());
            
            jLabel4.setBackground(new JLabel().getBackground());
            jLabel4.setForeground(new JLabel().getForeground());
            
            jLabel5.setBackground(new JLabel().getBackground());
            jLabel5.setForeground(new JLabel().getForeground());
            
            jLabel6.setBackground(new JLabel().getBackground());
            jLabel6.setForeground(new JLabel().getForeground());
            
            // ------------------------------------------------------------------------------- BUTTONS
            btnSave1.setBackground(new JButton().getBackground());
            btnSave1.setForeground(new JButton().getForeground());
            
            btnSave2.setBackground(new JButton().getBackground());
            btnSave2.setForeground(new JButton().getForeground());
            
            btnSave3.setBackground(new JButton().getBackground());
            btnSave3.setForeground(new JButton().getForeground());
            
            btnSave4.setBackground(new JButton().getBackground());
            btnSave4.setForeground(new JButton().getForeground());
            
            btnSave5.setBackground(new JButton().getBackground());
            btnSave5.setForeground(new JButton().getForeground());
            
            // ------------------------------------------------------------------------------- TEXT FIELDS
            tfSaveProfile1.setBackground(new JTextField().getBackground());
            tfSaveProfile1.setForeground(new JTextField().getForeground());
            
            tfSaveProfile2.setBackground(new JTextField().getBackground());
            tfSaveProfile2.setForeground(new JTextField().getForeground());
            
            tfSaveProfile3.setBackground(new JTextField().getBackground());
            tfSaveProfile3.setForeground(new JTextField().getForeground());
            
            tfSaveProfile4.setBackground(new JTextField().getBackground());
            tfSaveProfile4.setForeground(new JTextField().getForeground());
            
            tfSaveProfile5.setBackground(new JTextField().getBackground());
            tfSaveProfile5.setForeground(new JTextField().getForeground());
        }
        else if(theme.equals("dark")) {
            // ------------------------------------------------------------------------------- PANELS
            this.getContentPane().setBackground(Color.DARK_GRAY);
            
            panel1.setBackground(Color.DARK_GRAY);
            panel1.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            
            panel6.setBackground(Color.DARK_GRAY);
            panel6.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            
            panel7.setBackground(Color.DARK_GRAY);
            panel7.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            
            panel8.setBackground(Color.DARK_GRAY);
            panel8.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            
            panel9.setBackground(Color.DARK_GRAY);
            panel9.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            
            // ------------------------------------------------------------------------------- LABELS
            jLabel1.setBackground(Color.DARK_GRAY);
            jLabel1.setForeground(Color.LIGHT_GRAY);
            
            jLabel3.setBackground(Color.DARK_GRAY);
            jLabel3.setForeground(Color.LIGHT_GRAY);
            
            jLabel4.setBackground(Color.DARK_GRAY);
            jLabel4.setForeground(Color.LIGHT_GRAY);
            
            jLabel5.setBackground(Color.DARK_GRAY);
            jLabel5.setForeground(Color.LIGHT_GRAY);
            
            jLabel6.setBackground(Color.DARK_GRAY);
            jLabel6.setForeground(Color.LIGHT_GRAY);
            
            // ------------------------------------------------------------------------------- BUTTONS
            btnSave1.setBackground(Color.GRAY);
            btnSave1.setForeground(Color.WHITE);
            
            btnSave2.setBackground(Color.GRAY);
            btnSave2.setForeground(Color.WHITE);
            
            btnSave3.setBackground(Color.GRAY);
            btnSave3.setForeground(Color.WHITE);
            
            btnSave4.setBackground(Color.GRAY);
            btnSave4.setForeground(Color.WHITE);
            
            btnSave5.setBackground(Color.GRAY);
            btnSave5.setForeground(Color.WHITE);
            
            // ------------------------------------------------------------------------------- TEXT FIELDS
            tfSaveProfile1.setBackground(Color.DARK_GRAY);
            tfSaveProfile1.setForeground(Color.LIGHT_GRAY);
            
            tfSaveProfile2.setBackground(Color.DARK_GRAY);
            tfSaveProfile2.setForeground(Color.LIGHT_GRAY);
            
            tfSaveProfile3.setBackground(Color.DARK_GRAY);
            tfSaveProfile3.setForeground(Color.LIGHT_GRAY);
            
            tfSaveProfile4.setBackground(Color.DARK_GRAY);
            tfSaveProfile4.setForeground(Color.LIGHT_GRAY);
            
            tfSaveProfile5.setBackground(Color.DARK_GRAY);
            tfSaveProfile5.setForeground(Color.LIGHT_GRAY);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnSave2;
    private javax.swing.JButton btnSave3;
    private javax.swing.JButton btnSave4;
    private javax.swing.JButton btnSave5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel7;
    private javax.swing.JPanel panel8;
    private javax.swing.JPanel panel9;
    private javax.swing.JTextField tfSaveProfile1;
    private javax.swing.JTextField tfSaveProfile2;
    private javax.swing.JTextField tfSaveProfile3;
    private javax.swing.JTextField tfSaveProfile4;
    private javax.swing.JTextField tfSaveProfile5;
    // End of variables declaration//GEN-END:variables
}
