/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package happybuttons;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.plaf.basic.BasicMenuUI;

/**
 *
 * @author Michael Balibrea
 */
public class SettingsFrame extends javax.swing.JDialog {

    /**
     * Creates new form SettingsFrame
     */
    public SettingsFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        super.setTitle("Settings");
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/3-this.getSize().height/2);
        
        // set frame icon
        ImageIcon imgIcon = new ImageIcon(HappyButtons.documentsPathDoubleSlash + Utility.strDoubleSlash("\\HappyButtons\\res\\icon\\wave.png"));
        setIconImage(imgIcon.getImage());
        
        onLoad();
    }
    
    public void onLoad() {
        // setup checkbox
        if(MainFrame.enableAutosave.equals("off")) {
            chkAutosave.setSelected(false);
        }
        else {
            chkAutosave.setSelected(true);
        }
        
        // setup startup
        if(MainFrame.startup.equals("new")) {
            cboStartup.setSelectedIndex(0);
        }
        else {
            cboStartup.setSelectedIndex(1);
        }
        
        // setup video loop full screen
        if(MainFrame.fullScreenVL.equals("window")) {
            rbtnWindowed.setSelected(true);
        }
        else {
            rbtnFullScreen.setSelected(true);
        }
    }
    
    public void autosave() {
        UIProfile ui = new UIProfile();
        HappyButtons.dbo.autoSaveUISettings(HappyButtons.uiDB, ui);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        chkAutosave = new javax.swing.JCheckBox();
        lblStartup = new javax.swing.JLabel();
        cboStartup = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboVLScreen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rbtnWindowed = new javax.swing.JRadioButton();
        rbtnFullScreen = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(800, 400));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel1.setMaximumSize(new java.awt.Dimension(390, 92));
        jPanel1.setPreferredSize(new java.awt.Dimension(390, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkAutosave.setText("Enable autosave");
        chkAutosave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAutosaveActionPerformed(evt);
            }
        });
        jPanel1.add(chkAutosave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblStartup.setText("Startup:");
        jPanel1.add(lblStartup, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 66, -1, 30));

        cboStartup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Start new workspace", "Load previous profile" }));
        cboStartup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboStartupActionPerformed(evt);
            }
        });
        jPanel1.add(cboStartup, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 310, -1));

        jTabbedPane1.addTab("Save/Load", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Video loop Screen:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        cboVLScreen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Screen 1", "Screen 2", "Screen 3" }));
        cboVLScreen.setEnabled(false);
        jPanel2.add(cboVLScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));

        jLabel2.setText("Video loop display:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        buttonGroup1.add(rbtnWindowed);
        rbtnWindowed.setText("Windowed");
        rbtnWindowed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnWindowedActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnWindowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        buttonGroup1.add(rbtnFullScreen);
        rbtnFullScreen.setText("Full screen");
        rbtnFullScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFullScreenActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnFullScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jTabbedPane1.addTab("Display", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkAutosaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAutosaveActionPerformed
        if(chkAutosave.isSelected()) {
            MainFrame.enableAutosave = "on";
            MainFrame.itmAS.setUI(new CustomMenuUI());
            MainFrame.itmAS.setVisible(true);
        }
        else {
            MainFrame.enableAutosave = "off";
            MainFrame.itmAS.setVisible(false);
        }
        
        autosave();
    }//GEN-LAST:event_chkAutosaveActionPerformed

    private void cboStartupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboStartupActionPerformed
        if(cboStartup.getSelectedIndex() == 0) {
            MainFrame.startup = "new";
        }
        else {
            MainFrame.startup = "load";
        }
        
        autosave();
    }//GEN-LAST:event_cboStartupActionPerformed

    private void rbtnWindowedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnWindowedActionPerformed
        MainFrame.fullScreenVL = "window";
        autosave();
    }//GEN-LAST:event_rbtnWindowedActionPerformed

    private void rbtnFullScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFullScreenActionPerformed
        MainFrame.fullScreenVL = "full";
        autosave();
    }//GEN-LAST:event_rbtnFullScreenActionPerformed

    public class CustomMenuUI extends BasicMenuUI {
        protected void paintText(Graphics g, JComponent c, Rectangle textRect, String text) {
            if(!c.isEnabled()) {
                g.setColor(Color.GREEN); // Set the font color to blue for disabled JMenu
            }
            else {
                g.setColor(c.getForeground());
            }
            g.drawString(text, textRect.x, textRect.y + g.getFontMetrics().getAscent());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SettingsFrame dialog = new SettingsFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboStartup;
    private javax.swing.JComboBox<String> cboVLScreen;
    private javax.swing.JCheckBox chkAutosave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblStartup;
    public static javax.swing.JRadioButton rbtnFullScreen;
    public static javax.swing.JRadioButton rbtnWindowed;
    // End of variables declaration//GEN-END:variables
}
